#!/usr/bin/env python3
"""
Portfolio CMS Data Server
Serves static files + handles POST /api/save-data to persist CMS content to disk.
"""
import http.server
import json
import os
import urllib.parse
from pathlib import Path

PORT = 8000
BASE_DIR = Path(__file__).parent.resolve()
DATA_FILE = BASE_DIR / 'portfolio-data.json'
JS_FILE   = BASE_DIR / 'portfolio-data.js'

class CmsHandler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(BASE_DIR), **kwargs)

    def end_headers(self):
        # CORS + no-cache for API routes
        if self.path.startswith('/api/'):
            self.send_header('Access-Control-Allow-Origin', '*')
            self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
            self.send_header('Access-Control-Allow-Headers', 'Content-Type')
            self.send_header('Cache-Control', 'no-store')
        super().end_headers()

    def do_OPTIONS(self):
        self.send_response(200)
        self.end_headers()

    def do_GET(self):
        # Serve portfolio-data.json if it exists, else return {}
        if self.path == '/api/load-data':
            if DATA_FILE.exists():
                data = DATA_FILE.read_text(encoding='utf-8')
            else:
                data = '{}'
            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(data.encode('utf-8'))
            return
        super().do_GET()

    def do_POST(self):
        if self.path == '/api/save-data':
            try:
                length = int(self.headers.get('Content-Length', 0))
                body = self.rfile.read(length)
                parsed = json.loads(body)
                json_str = json.dumps(parsed, ensure_ascii=False, indent=2)
                # Write JSON file
                DATA_FILE.write_text(json_str, encoding='utf-8')
                # Write JS file — loaded as <script> tag for zero-async sync
                JS_FILE.write_text(
                    f'/* Auto-generated by CMS server — do not edit */\nwindow.__PORTFOLIO_DATA__ = {json_str};\n',
                    encoding='utf-8'
                )
                self.send_response(200)
                self.send_header('Content-Type', 'application/json')
                self.end_headers()
                self.wfile.write(b'{"ok":true}')
                print(f'[CMS] portfolio-data.js + .json saved ({len(body)} bytes)')
            except Exception as e:
                self.send_response(500)
                self.send_header('Content-Type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps({'ok': False, 'error': str(e)}).encode())
                print(f'[CMS] Save error: {e}')
            return
        self.send_response(404)
        self.end_headers()

    def log_message(self, fmt, *args):
        first = args[0] if args else ''
        if isinstance(first, str) and '/api/' in first:
            super().log_message(fmt, *args)

if __name__ == '__main__':
    import socketserver
    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.TCPServer(('0.0.0.0', PORT), CmsHandler) as httpd:
        print(f'✅ Portfolio server running at http://localhost:{PORT}')
        print(f'   Serving files from: {BASE_DIR}')
        print(f'   Data file: {DATA_FILE}')
        print(f'   POST /api/save-data  → saves CMS data to disk')
        print(f'   GET  /api/load-data  → returns saved CMS data')
        httpd.serve_forever()
